const fs = require('fs');
let c = fs.readFileSync('app/(dashboard)/chat/page.tsx', 'utf8');

c = c.replace(/{ value: "en-IN", label: "EN" }/g, '{ value: "en-IN", label: "English" }');
c = c.replace(/{ value: "hi-IN", label: "HI" }/g, '{ value: "hi-IN", label: "Hindi" }');
c = c.replace(/{ value: "bn-IN", label: "BN" }/g, '{ value: "bn-IN", label: "Bengali" }');
c = c.replace(/{ value: "af-ZA", label: "AF" }/g, '{ value: "af-ZA", label: "Afrikaans" }');
c = c.replace(/{ value: "ar-SA", label: "AR" }/g, '{ value: "ar-SA", label: "Arabic" }');
c = c.replace(/{ value: "bg-BG", label: "BG" }/g, '{ value: "bg-BG", label: "Bulgarian" }');
c = c.replace(/{ value: "cs-CZ", label: "CS" }/g, '{ value: "cs-CZ", label: "Czech" }');
c = c.replace(/{ value: "da-DK", label: "DA" }/g, '{ value: "da-DK", label: "Danish" }');
c = c.replace(/{ value: "de-DE", label: "DE" }/g, '{ value: "de-DE", label: "German" }');
c = c.replace(/{ value: "el-GR", label: "EL" }/g, '{ value: "el-GR", label: "Greek" }');
c = c.replace(/{ value: "es-ES", label: "ES" }/g, '{ value: "es-ES", label: "Spanish" }');
c = c.replace(/{ value: "fi-FI", label: "FI" }/g, '{ value: "fi-FI", label: "Finnish" }');
c = c.replace(/{ value: "fr-FR", label: "FR" }/g, '{ value: "fr-FR", label: "French" }');
c = c.replace(/{ value: "gu-IN", label: "GU" }/g, '{ value: "gu-IN", label: "Gujarati" }');
c = c.replace(/{ value: "he-IL", label: "HE" }/g, '{ value: "he-IL", label: "Hebrew" }');
c = c.replace(/{ value: "hr-HR", label: "HR" }/g, '{ value: "hr-HR", label: "Croatian" }');
c = c.replace(/{ value: "hu-HU", label: "HU" }/g, '{ value: "hu-HU", label: "Hungarian" }');
c = c.replace(/{ value: "id-ID", label: "ID" }/g, '{ value: "id-ID", label: "Indonesian" }');
c = c.replace(/{ value: "it-IT", label: "IT" }/g, '{ value: "it-IT", label: "Italian" }');
c = c.replace(/{ value: "ja-JP", label: "JA" }/g, '{ value: "ja-JP", label: "Japanese" }');
c = c.replace(/{ value: "kn-IN", label: "KN" }/g, '{ value: "kn-IN", label: "Kannada" }');
c = c.replace(/{ value: "ko-KR", label: "KO" }/g, '{ value: "ko-KR", label: "Korean" }');
c = c.replace(/{ value: "ml-IN", label: "ML" }/g, '{ value: "ml-IN", label: "Malayalam" }');
c = c.replace(/{ value: "mr-IN", label: "MR" }/g, '{ value: "mr-IN", label: "Marathi" }');
c = c.replace(/{ value: "nl-NL", label: "NL" }/g, '{ value: "nl-NL", label: "Dutch" }');
c = c.replace(/{ value: "no-NO", label: "NO" }/g, '{ value: "no-NO", label: "Norwegian" }');
c = c.replace(/{ value: "pa-IN", label: "PA" }/g, '{ value: "pa-IN", label: "Punjabi" }');
c = c.replace(/{ value: "pl-PL", label: "PL" }/g, '{ value: "pl-PL", label: "Polish" }');
c = c.replace(/{ value: "pt-BR", label: "PT" }/g, '{ value: "pt-BR", label: "Portuguese" }');
c = c.replace(/{ value: "ro-RO", label: "RO" }/g, '{ value: "ro-RO", label: "Romanian" }');
c = c.replace(/{ value: "ru-RU", label: "RU" }/g, '{ value: "ru-RU", label: "Russian" }');
c = c.replace(/{ value: "sv-SE", label: "SV" }/g, '{ value: "sv-SE", label: "Swedish" }');
c = c.replace(/{ value: "ta-IN", label: "TA" }/g, '{ value: "ta-IN", label: "Tamil" }');
c = c.replace(/{ value: "te-IN", label: "TE" }/g, '{ value: "te-IN", label: "Telugu" }');
c = c.replace(/{ value: "tr-TR", label: "TR" }/g, '{ value: "tr-TR", label: "Turkish" }');
c = c.replace(/{ value: "uk-UA", label: "UK" }/g, '{ value: "uk-UA", label: "Ukrainian" }');
c = c.replace(/{ value: "ur-IN", label: "UR" }/g, '{ value: "ur-IN", label: "Urdu" }');
c = c.replace(/{ value: "vi-VN", label: "VI" }/g, '{ value: "vi-VN", label: "Vietnamese" }');
c = c.replace(/{ value: "zh-CN", label: "ZH" }/g, '{ value: "zh-CN", label: "Chinese" }');


fs.writeFileSync('app/(dashboard)/chat/page.tsx', c);
